// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ4A85nnJKpdkSZcA8FTuw5Yn97sdAH8w',
    appId: '1:813850757085:web:34475a59cb8dea47e45834',
    messagingSenderId: '813850757085',
    projectId: 'taskrush-9f8a4',
    authDomain: 'taskrush-9f8a4.firebaseapp.com',
    storageBucket: 'taskrush-9f8a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELYeV3pf2cSLIgPL8tqRDletAQRD4kpQ',
    appId: '1:813850757085:android:a2220384caae29f6e45834',
    messagingSenderId: '813850757085',
    projectId: 'taskrush-9f8a4',
    storageBucket: 'taskrush-9f8a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_yqMpPs0JNlA1L7C-xvv1ZtqoYR-6Zm0',
    appId: '1:813850757085:ios:9ef28269e75ce13de45834',
    messagingSenderId: '813850757085',
    projectId: 'taskrush-9f8a4',
    storageBucket: 'taskrush-9f8a4.firebasestorage.app',
    iosClientId: '813850757085-appt8l43sfke8eflfme3jukq1ruk2b9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskRushMobileAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_yqMpPs0JNlA1L7C-xvv1ZtqoYR-6Zm0',
    appId: '1:813850757085:ios:9ef28269e75ce13de45834',
    messagingSenderId: '813850757085',
    projectId: 'taskrush-9f8a4',
    storageBucket: 'taskrush-9f8a4.firebasestorage.app',
    iosClientId: '813850757085-appt8l43sfke8eflfme3jukq1ruk2b9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskRushMobileAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ4A85nnJKpdkSZcA8FTuw5Yn97sdAH8w',
    appId: '1:813850757085:web:0ea32dcaa643ee73e45834',
    messagingSenderId: '813850757085',
    projectId: 'taskrush-9f8a4',
    authDomain: 'taskrush-9f8a4.firebaseapp.com',
    storageBucket: 'taskrush-9f8a4.firebasestorage.app',
  );
}
